Repository Inversed-Tech/eyelid, pull requests merged in 2024-04, with the labels that each got.

#33 Enforce `MAX_DEGREE` and create efficient `X^n` methods
  .github/workflows/lint-spell.yml
  Cargo.toml
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/fq.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/modulus.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/trivial.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
Labels: enhancement

#42 Enable compiler optimization settings that reliably increase performance in the Rust configs
  .cargo/config.toml
  .github/workflows/ci-bench.yml
  .github/workflows/ci-build.yml
  .github/workflows/ci-test.yml
  .github/workflows/lint-clippy.yml
  .github/workflows/lint-docs.yml
  .github/workflows/lint-rustfmt.yml
  Cargo.toml
Labels: enhancement, performance

#32 Flat Karatsuba optimization
  Cargo.lock
  Cargo.toml
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/fq/fq_tiny.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/trivial.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
Labels: enhancement, extra-reviews

#57 Monitor benchmark changes on each PR
  .github/workflows/ci-bench-changes.yml
  eyelid-matcher/Cargo.toml
  eyelid-test/Cargo.toml
Labels: testing, performance

#47 Allow polynomials with different modulus degrees, by making the maximum degree generic
  Cargo.toml
  eyelid-match-ops/Cargo.toml
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/fq.rs
  eyelid-match-ops/src/primitives/poly/fq/fq79.rs
  eyelid-match-ops/src/primitives/poly/fq/fq_tiny.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/modulus.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/trivial.rs
  eyelid-match-ops/src/primitives/poly/test/gen.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
Labels: enhancement

#52 Move multiplication to a new mul.rs module
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/mul.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
Labels: cleanup

#60 Give permissions for performance comments on commits
  .github/workflows/ci-bench-changes.yml
Labels: bug, performance

#61 Fix clippy permissions and names
  .github/workflows/lint-clippy.yml
Labels: bug, automation

#48 Extended GCD and Inverses
  eyelid-match-ops/Cargo.toml
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/modulus.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/mul.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/trivial.rs
  eyelid-match-ops/src/primitives/poly/test.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
Labels: enhancement, extra-reviews

#66 Try to fix benchmark cache updates and add debug logs
  .github/workflows/ci-bench-changes.yml
Labels: bug, performance, automation

#67 Fix caching of benchmark results
  .github/workflows/ci-bench-changes.yml
Labels: bug, performance, automation

#68 Skip benchmark cache save on PRs
  .github/workflows/ci-bench-changes.yml
Labels: bug, performance, automation
