Repository Inversed-Tech/eyelid, pull requests merged in 2024-05, with the labels that each got.

#69 Basic key generation
  Cargo.lock
  Cargo.toml
  eyelid-match-ops/Cargo.toml
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives.rs
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/inv.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/yashe.rs
  eyelid-match-ops/src/primitives/yashe/test.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: enhancement, deliverable

#65 Add YASHE key generation and full iris bit length polynomial benchmarks
  .github/workflows/ci-bench-changes.yml
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/yashe.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: testing, performance

#75 Make the const generic degree into a generic trait struct
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/inv.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/modulus.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/mul.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/trivial.rs
  eyelid-match-ops/src/primitives/poly/test/gen.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
  eyelid-match-ops/src/primitives/yashe.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: enhancement

#79 1. Make `Coeff` into an associated type of the `PolyConf` trait
  Cargo.toml
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/fq.rs
  eyelid-match-ops/src/primitives/poly/fq/fq79.rs
  eyelid-match-ops/src/primitives/poly/fq/fq_tiny.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/inv.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/modulus.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/mul.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/trivial.rs
  eyelid-match-ops/src/primitives/poly/test/gen.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
  eyelid-match-ops/src/primitives/yashe.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: cleanup

#80 Add a generic `YasheConf` trait and use it instead of an inner config struct
  .cargo/config.toml
  .gitignore
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/yashe.rs
  eyelid-match-ops/src/primitives/yashe/conf.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: cleanup

#83 Clean up dependencies and make benchmark names shorter
  .github/workflows/ci-bench-changes.yml
  Cargo.toml
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
Labels: testing, cleanup, automation

#81 Polycode: polynomial encodings of iris codes with mask and rotations
  Cargo.lock
  Cargo.toml
  eyelid-match-ops/Cargo.toml
  eyelid-match-ops/src/encoded.rs
  eyelid-match-ops/src/encoded/test.rs
  eyelid-match-ops/src/encoded/test/matching.rs
  eyelid-match-ops/src/plaintext.rs
  eyelid-match-ops/src/plaintext/test.rs
  eyelid-match-ops/src/plaintext/test/gen.rs
  eyelid-match-ops/src/plaintext/test/matching.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
Labels: enhancement, deliverable

#82 Implementation of encryption and decryption
  .github/workflows/ci-bench-changes.yml
  Cargo.lock
  Cargo.toml
  eyelid-match-ops/Cargo.toml
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/mul.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/yashe.rs
  eyelid-match-ops/src/primitives/yashe/conf.rs
  eyelid-match-ops/src/primitives/yashe/test.rs
  eyelid-match-ops/src/primitives/yashe/test/encdec.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: enhancement, deliverable

#85 Add an IrisConf trait, but don't convert function code to it yet
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/conf.rs
  eyelid-match-ops/src/encoded.rs
  eyelid-match-ops/src/iris.rs
  eyelid-match-ops/src/iris/conf.rs
  eyelid-match-ops/src/lib.rs
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/modulus.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
  eyelid-match-ops/src/primitives/yashe/conf.rs
  eyelid-match-ops/src/primitives/yashe/test/encdec.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: enhancement, cleanup, deliverable

#96 Fix a floating point equality bug and document why it happened
  eyelid-match-ops/src/primitives/yashe/conf.rs
Labels: bug, testing
