Repository Inversed-Tech/eyelid, pull requests merged in 2024-06, with the labels that each got.

#97 Make the `plaintext` and `encoded` modules generic over `IrisConf`
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/encoded.rs
  eyelid-match-ops/src/encoded/conf.rs
  eyelid-match-ops/src/encoded/test/matching.rs
  eyelid-match-ops/src/iris/conf.rs
  eyelid-match-ops/src/lib.rs
  eyelid-match-ops/src/plaintext.rs
  eyelid-match-ops/src/plaintext/test.rs
  eyelid-match-ops/src/plaintext/test/gen.rs
  eyelid-match-ops/src/plaintext/test/matching.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/mul.rs
  eyelid-match-ops/src/primitives/yashe/conf.rs
Labels: enhancement, cleanup, deliverable

#98 Implement homomorphic operations
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/conf.rs
  eyelid-match-ops/src/iris/conf.rs
  eyelid-match-ops/src/lib.rs
  eyelid-match-ops/src/primitives/poly.rs
  eyelid-match-ops/src/primitives/poly/fq.rs
  eyelid-match-ops/src/primitives/poly/fq/fq66.rs
  eyelid-match-ops/src/primitives/poly/fq/fq66bn.rs
  eyelid-match-ops/src/primitives/poly/fq/fq79bn.rs
  eyelid-match-ops/src/primitives/poly/fq/fq_tiny_bn.rs
  eyelid-match-ops/src/primitives/poly/modular_poly.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/mul.rs
  eyelid-match-ops/src/primitives/yashe.rs
  eyelid-match-ops/src/primitives/yashe/conf.rs
  eyelid-match-ops/src/primitives/yashe/test.rs
  eyelid-match-ops/src/primitives/yashe/test/encdec.rs
  eyelid-match-ops/src/primitives/yashe/test/hom.rs
Labels: enhancement, cleanup, deliverable

#105 Change iris dimensions to match the report, and fix encoded polynomial block configurations
  eyelid-match-ops/benches/match-ops.rs
  eyelid-match-ops/src/conf.rs
  eyelid-match-ops/src/encoded.rs
  eyelid-match-ops/src/encoded/conf.rs
  eyelid-match-ops/src/encoded/test/matching.rs
  eyelid-match-ops/src/iris/conf.rs
  eyelid-match-ops/src/lib.rs
  eyelid-match-ops/src/plaintext/test/matching.rs
  eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs
  eyelid-match-ops/src/primitives/poly/test/inv.rs
  eyelid-match-ops/src/primitives/poly/test/mul.rs
  eyelid-match-ops/src/primitives/yashe/conf.rs
  eyelid-match-ops/src/primitives/yashe/test/encdec.rs
  eyelid-match-ops/src/primitives/yashe/test/hom.rs
  eyelid-match-ops/src/primitives/yashe/test/keygen.rs
Labels: bug, cleanup

#110 Optimise test builds to speed up tests
  Cargo.toml
Labels: automation
